### ISSUE TITLE
Cabana project version has never been updated

### ISSUE THREAD

**Issue by dalg24** [ECP-copa/Cabana#104]
Cabana project version shows 0.1.0 in CMake.
https://github.com/ECP-copa/Cabana/blob/e3327d7b5eb97694ddbf7ede2356c5c8d6166127/CMakeLists.txt#L9

_Originally posted by @dalg24 in https://github.com/ECP-copa/Cabana/pull/85#issuecomment-472476023_

**Comment by sslattery** [comment]
What about #85?
