### ISSUE TITLE
Improve FindKOKKOS.cmake

### ISSUE THREAD

**Issue by junghans** [ECP-copa/Cabana#11]
Currently we add `-ldl` and `-fopenmp` manually, which isn't great.

However, KOKKOS installs `kokkos_generated_settings.cmake`, which we could include in our find macro and then generate a imported target for kokkos.

/cc @rfbird

**Comment by rfbird** [comment]
Agreed, this would improve the spack package too

**Comment by junghans** [comment]
yeah!
