### ISSUE TITLE
FindKokkos `INTERFACE_COMPILE_OPTIONS` propogation

### ISSUE THREAD

**Issue by rfbird** [ECP-copa/Cabana#110]
@junghans will know better than me on this, but I think Gy and I just bumped into a problem.

Currently, we set `INTERFACE_COMPILE_OPTIONS`, and when we start using a Fortran compiler, the flags also propagate to there.

I think we need a way to limit the flags to be `CXX` only. A quick google suggests something like: 

` INTERFACE_COMPILE_OPTIONS "$<$<COMPILE_LANGUAGE:CXX>:${KOKKOS_CXX_FLAGS_WITHOUT_INCLUDES}>"`

There could definitely be a better cmake way to avoid this problem also

Edit: In case I'm way off base with this, the symptom we're seeing is that the Fortran compiler is getting passed flags which include CXX specific things, and as far as I can tell it seems to propagate up from `KOKKOS_CXX_FLAGS_WITHOUT_INCLUDES`

**Comment by guangyechen** [comment]
@rfbird 's solution seems working for me. Before that, fortran flags would inherit CXX ones, (which seems to be from Kokkos), and whatever used in `-DCMAKE_Fortran_FLAGS='your-flags'` will only add on those.

**Comment by sslattery** [comment]
Can you guys make a PR for this? I'm assuming you can update the CMake to reflect this.

**Comment by rfbird** [comment]
Do you want to do this @guangyechen ? I don't know what code you ended up with

**Comment by guangyechen** [comment]
@rfbird I have already done this in the pr #111. @sslattery do you want a separate one?

**Comment by sslattery** [comment]
No doesn't need to be separate - just want to document that #111 will close this issue. Looks like GitHub has already picked up on this

**Comment by guangyechen** [comment]
Sounds good.

**Comment by guangyechen** [comment]
@rfbird It looks like the fix is only for compile options. The Kokkos flags are still there in the linking flags:
```
[ 95%] Linking Fortran executable ForParallelFor
cd /Users/gchen/Research/Cabana/build/core/fortran-example/tutorial/05_parallel_for && /opt/local/bin/cmake -E cmake_link_script CMakeFiles/ForParallelFor.dir/link.txt --verbose=1
/opt/pgi/osx86-64/18.10/bin/pgfortran  -pgc++libs -ta=multicore -g -O0 -Mbounds CMakeFiles/ForParallelFor.dir/Fortran_main.f90.o CMakeFiles/ForParallelFor.dir/Fortran_kernels.F90.o CMakeFiles/ForParallelFor.dir/parallel_for_example.cpp.o  -o ForParallelFor  -L/opt/local/lib/gcc6/gcc/x86_64-apple-darwin17/6.5.0  -L/opt/local/lib/gcc6  -L/usr/local/lib ../../../src/libcabanacore.a /Users/gchen/Research/kokkos/build/install/lib/libkokkos.a -ldl -fopenmp -lstdc++ -lgcc_ext.10.5
pgfortran-Error-Unknown switch: -fopenmp
make[2]: *** [core/fortran-example/tutorial/05_parallel_for/ForParallelFor] Error 1
make[1]: *** [core/fortran-example/tutorial/05_parallel_for/CMakeFiles/ForParallelFor.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by rfbird** [comment]
> @rfbird It looks like the fix is only for compile options. The Kokkos flags are still there in the linking flags:
> 
> ```
> [ 95%] Linking Fortran executable ForParallelFor
> cd /Users/gchen/Research/Cabana/build/core/fortran-example/tutorial/05_parallel_for && /opt/local/bin/cmake -E cmake_link_script CMakeFiles/ForParallelFor.dir/link.txt --verbose=1
> /opt/pgi/osx86-64/18.10/bin/pgfortran  -pgc++libs -ta=multicore -g -O0 -Mbounds CMakeFiles/ForParallelFor.dir/Fortran_main.f90.o CMakeFiles/ForParallelFor.dir/Fortran_kernels.F90.o CMakeFiles/ForParallelFor.dir/parallel_for_example.cpp.o  -o ForParallelFor  -L/opt/local/lib/gcc6/gcc/x86_64-apple-darwin17/6.5.0  -L/opt/local/lib/gcc6  -L/usr/local/lib ../../../src/libcabanacore.a /Users/gchen/Research/kokkos/build/install/lib/libkokkos.a -ldl -fopenmp -lstdc++ -lgcc_ext.10.5
> pgfortran-Error-Unknown switch: -fopenmp
> make[2]: *** [core/fortran-example/tutorial/05_parallel_for/ForParallelFor] Error 1
> make[1]: *** [core/fortran-example/tutorial/05_parallel_for/CMakeFiles/ForParallelFor.dir/all] Error 2
> make: *** [all] Error 2
> ```

My guess is @junghans will know best here

**Comment by junghans** [comment]
I guess `-fopenmp` is inherited from Kokkos. Did you compile kokkos with PGI as well?

**Comment by guangyechen** [comment]
No. I was using gcc. 
If I use pgc++ for kokkos, then it inherits the c++ flags "-mp -lpgatm -lc++" from Kokkos, which is preferred to be removed, because the linker is pgfortran.

**Comment by guangyechen** [comment]
It looks like it works as long as we use the same PGI compilers for Kokkos and Cabana with Fortran examples. Mixing different compilers for the C++ and Fortran codes could create many problems in the compilation and at runtime.

**Comment by rfbird** [comment]
Per Guangye's comment, we met on this today deciding it's only an issue if you try mix compilers (e.g `g++` and `pgfortran`). It was my conclusion we should avoid this, and in the Cuda Fortran case just marry down to the PGI tool chain. I'm really not interested in getting into a case where we need to do things like link both the PGI and GCC OpenMP libraries unless someone gives us a good use case

Close for now?

**Comment by sslattery** [comment]
I think that seems reasonable if the goal is CUDA Fortran support. @ascheinb Do you have an opinion on this? Does this reflect how you are compiling XGC?

**Comment by ascheinb** [comment]
Yes, I'm always matching compilers. On Titan, this didn't work as smoothly - there was some dependency built with an outdated compiler and I think we had to do a workaround mixing compilers. But Titan is shutting down in two months and that issue shouldn't happen moving forward. On Summit, for example, I've compiled everything with PGI and it's running fine.

**Comment by sslattery** [comment]
Closing per Aaron's comments that this is his required behavior for Summit.
