### ISSUE TITLE
Clean up .travis.yml after Doxygen-1.8.16 made it on Travis

### ISSUE THREAD

**Issue by junghans** [ECP-copa/Cabana#112]
Remove https://github.com/ECP-copa/Cabana/blob/620cb1a96deb4299728c2ec254aa12e47ec0b0ef/.travis.yml#L96-L99 after Doxygen-1.8.16 or higher is available on Travis.

**Comment by sslattery** [comment]
@junghans Do we have the newest Doxygen on Travis needed to address this issue?

**Comment by junghans** [comment]
As of today still: `doxygen amd64 1.8.11-1ubuntu0.1`
