### ISSUE TITLE
Switch CI back to release version of AMPI

### ISSUE THREAD

**Issue by junghans** [ECP-copa/Cabana#119]
Currently we are using the git master version of Charm++ to workaround this issue mentioned in https://github.com/ECP-copa/Cabana/pull/113#issuecomment-479234664. This is a bit brittle.

Let's switch back to a release version of Charm++ once a version later than 6.9.0 got released.

**Comment by sslattery** [comment]
Expect a Charm++ release in the next few weeks to resolve

**Comment by sslattery** [comment]
No update to Charm++ as of today

**Comment by junghans** [comment]
@evan-charmworks any plan for a new release?

**Comment by evan-charmworks** [comment]
Yes, we are close to issuing a release candidate of Charm++ 6.10. We will do so once the handful of remaining issues are resolved and our nightly build testing shows no failures.

https://github.com/UIUC-PPL/charm/milestones/6.10.0
http://charm.cs.illinois.edu/autobuild/cur/

**Comment by sslattery** [comment]
Will close when #171 is merged because we are not using AMPI right now
