### ISSUE TITLE
wiki updates

### ISSUE THREAD

**Issue by guangyechen** [ECP-copa/Cabana#12]
The docs dir was Stuart's original attempt to generate something that gitlab would render. The GitHub wiki is intended to replace the docs folder at the end of the day - one of the things we should be able to remove for the release! 

I have made an attempt to migrate the doc dir to the wiki, and added a preliminary benchmarks page.

**Comment by rfbird** [comment]
I was going to go over the build instructions and stream line them some, should I do that inside the wiki ?

**Comment by rfbird** [comment]
Also maybe making a PR which deletes the `docs` dir is a good idea one all the content is on the wiki?

**Comment by guangyechen** [comment]
Yes. Doing it inside the wiki would be better. You can pull just the wiki itself and work on that, or edit it online.

**Comment by rfbird** [comment]
OK i'll try do that today/soon

**Comment by sslattery** [comment]
OK I next I think we need a wiki page of each of the concepts with details on the API for each of the following in the 0.1 release:

1) Tuple
2) SoA
3) AoSoA
4) Slice
5) DeepCopy
6) Sort
7) LinkedCellList
8) NeighborList/VerletList

I think they make the most sense in that order.

**Comment by guangyechen** [comment]
From user perspective, should just AOSOA that is needed?

**Comment by sslattery** [comment]
To clarify even further I would like to have a programming guide similar to what Kokkos has provided: https://github.com/kokkos/kokkos/wiki/Programming-Guide%3A-Core. For example, something like the page on the view class for each thing I have listed above would be ideal: https://github.com/kokkos/kokkos/wiki/View

**Comment by rfbird** [comment]
> OK I next I think we need a wiki page of each of the concepts with details on the API for each of the following in the 0.1 release:
> 
> 1. Tuple
> 2. SoA
> 3. AoSoA
> 4. Slice
> 5. DeepCopy
> 6. Sort
> 7. LinkedCellList
> 8. NeighborList/VerletList
> 
> I think they make the most sense in that order.

I started adding some minimal pages to address these topics: 

https://github.com/ECP-copa/Cabana/wiki/Tuple

My plan is to draft the outline and then we can each go in and add more details

**Comment by rfbird** [comment]
Are we happy with this? Thanks for updating the pages/example links Stu

**Comment by sslattery** [comment]
I'm OK with this for now. I could easily spend another hour tweaking each page.
