### ISSUE TITLE
Enhance Fortran Interface 

### ISSUE THREAD

**Issue by rfbird** [ECP-copa/Cabana#121]
Through discussions, greatly informed by #103, we have identified lots of improvements that can be added to the Fortran interface. Some great nexts steps these include but are not limited to:

- [ ] Remove the dependency on static data pointers, likely instead passing pointers
- [ ] Abstract some of "portability" type macros Aaron had to introduce in his XCG port 
- [ ] Implement an unmanaged AoSoA such that it can wrap Fortran allocated memory (#114)

**Comment by sslattery** [comment]
As we do this consider package design - do we have a new Fortran interface package or do we add this into the core?

**Comment by sslattery** [comment]
@rfbird can we move this issue to the new `advanced-fortran-examples` repo?

**Comment by rfbird** [comment]
Sure. I think this issue was more focused on cleaning out some of Arrons nasty macros. It definitely fits under the `advance-FORTRAN-examples` but does not fit directly under the current work there

**Comment by sslattery** [comment]
I am tempted to backlog then as those interfaces are no longer a priority for XGC

**Comment by rfbird** [comment]
Agreed. It’s tightly coupled to code that’s gone/going away
