### ISSUE TITLE
Compiler warnings with Cuda 10.1

### ISSUE THREAD

**Issue by ascheinb** [ECP-copa/Cabana#138]
I compiled Cabana with gcc and Cuda 10.1 on summit. It compiled without errors, but I got hundreds of these warnings:

`warning: calling a __host__ function("std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string") from a __host__ __device__ function("Cabana::Slice<double [3][2],  ::Kokkos::HostSpace,  ::Cabana::DefaultAccessMemory, (int)8, (int)172> ::~Slice") is not allowed`

(The specific functions in quotes varied.)

Not sure why this is a warning rather than an error, but hopefully it will still run okay.

**Comment by sslattery** [comment]
Yes I just noticed those after they did the update. I will be doing a PR to fix. It's weird because the things that they are complaining about should be STL supported functions (e.g. `std::extent`)

**Comment by ascheinb** [comment]
Okay cool. Will I need the fix before running, or is it just to resolve the warnings?

**Comment by sslattery** [comment]
I've been running with it and it seems OK. The fix would be to just resolve warnings.
