### ISSUE TITLE
Passing Slice to Distributor causes a seg fault

### ISSUE THREAD

**Issue by rfbird** [ECP-copa/Cabana#153]
The distributor accepts a `Cabana::slice` in the constructor (which is good), but it then expects the `.extents` call to work like a `Kokkos::view` and ends up creating arrays that are too small, ultimately leading to an out of bounds.

https://github.com/ECP-copa/Cabana/blob/master/core/src/Cabana_CommunicationPlan.hpp#L122

**Comment by sslattery** [comment]
My bad...
