### ISSUE TITLE
Merge Cajita with Cabana

### ISSUE THREAD

**Issue by sslattery** [ECP-copa/Cabana#197]
Moving Cajita functionality into Cabana will allow for better implementations of particle communication algorithms, tighter coupling in the implementation of PIC codes, sharing build/test infrastructure between the two libraries, and focusing developers on a single code base. The following strategy is proposed:

- [x] Update both repositories to use Kokkos 3.0 including all CMake upgrades (e.g. #165)

- [x] Ensure Cajita will work with CudaUVM - this largely is identifying the places where `Kokkos::fence()` is needed.

- [x] Merge/close all existing Cajita pull requests

- [x] Identify name collisions between the two libraries and adjust as necessary

- [x] Devise a preliminary structure for the new library in terms of directories and targets

- [x] Merge in Cajita with `git merge --allow-unrelated-histories`

- [x] Make issues for new algorithms that can now be implemented with both (e.g. better halos and  distributors with geometric support)

**Comment by streeve** [comment]
First, is it worth adding doxygen and minimal wiki documentation before the merge? 

Is there a strong preference for a single `src` folder or split `particle`, `particle-grid`, and/or `grid` subfolders?

And following that, do we want the `Halo` class to contain both particle and grid halos, or split into `ParticleHalo` and `GridHalo`? Should some classes that only apply to grids be renamed to be more clear (`IndexSpace` -> `GridIndexSpace`)?

**Comment by sslattery** [comment]
I'm unsure on the source directory structure yet. One thing I have been thinking is if we should use namespaces to separate classes (e.g. `Cabana::Particle::Halo` and `Cabana::Grid::Halo`) instead of merging them or renaming them. Then the functions like `Cabana::p2g` make sense for the particle-grid interactions.

**Comment by streeve** [comment]
Initial merge done in #235
