### ISSUE TITLE
programming guide code links broken

### ISSUE THREAD

**Issue by cwsmith** [ECP-copa/Cabana#240]
The links to code in the wiki's Programming Guide:
https://github.com/ECP-copa/Cabana/wiki/Programming-Guide
include the `core` sub-directory in the url which no longer exists.  For example,
the 'Tuple Tutorial' link on this page:
https://github.com/ECP-copa/Cabana/wiki/Tuple
should point to 
https://github.com/ECP-copa/Cabana/blob/master/example/tutorial/02_tuple/tuple_example.cpp
instead of
https://github.com/ECP-copa/Cabana/blob/master/core/example/tutorial/02_tuple/tuple_example.cpp .

**Comment by streeve** [comment]
Thanks for pointing that out - I believe I fixed all those wiki links
