### ISSUE TITLE
building of Unit tests fail to build with icpc 

### ISSUE THREAD

**Issue by pvelesko** [ECP-copa/Cabana#255]
When building with icpc 2018 (also tried with 2019) with unit tests enabled, I get the following error:
`[ 36%] Building CXX object cajita/unit_test/CMakeFiles/Cajita_Array_test_SERIAL.dir/unit_test_main.cpp.o
In file included from /home/pvelesko/local/cabana/core/src/Cabana_AoSoA.hpp(17),
                 from /home/pvelesko/local/cabana/core/unit_test/tstLinkedCellList.hpp(12),
                 from /home/pvelesko/local/cabana/build_kokkos_icpc/core/unit_test/SERIAL/tstLinkedCellList_SERIAL.cpp(2):
/home/pvelesko/local/cabana/core/src/Cabana_SoA.hpp(125): error: namespace "std" has no member "index_sequence"
  struct SoAImpl<VectorLength, std::index_sequence<Indices...>, Types...>
`

I searched and replaced all CXX_STANDARD 11 references to 14 but no change. This error doesn't show up when building with llvm toolchain.

**Comment by sslattery** [comment]
Did you enable `C++14` in the Kokkos build?

**Comment by pvelesko** [comment]
Upgrading to newer gcc solved the issue
