### ISSUE TITLE
identifier "is_aosoa" is undefined

### ISSUE THREAD

**Issue by pvelesko** [ECP-copa/Cabana#256]
No idea why this happens.. Looking at the file, I see the include but somehow it fails with the following error:

`gmake[1]: Leaving directory `/home/pvelesko/XGC-Devel/XGC_core'
/usr/bin/gmake -C ./XGC_core/cpp objects_cpp
gmake[1]: Entering directory `/home/pvelesko/XGC-Devel/XGC_core/cpp'
mpiicpc -Wall -qopenmp -std=c++14  -lstdc++ -DPSPLINE -DUSE_BICUB_MOD -DUSE_ONE_D_I_CUB_MOD -DV_PERP -DSOLVERLU  -DUSE_INQUIRE_DIRECTORY -DITER_GRID -DCAM_TIMERS -DXGC1 -DUSE_CAB -DUSE_CAB_CPP -DUSE_CAB_OMP=1 -DUSE_CAB_GPU=0 -DUSE_ARRAY_REPLICATION -DSIMD_SIZE=32 -DVEC_LEN=32  -I/home/pvelesko/local/kokkos_mainline/build_icpx/install/include -I/home/pvelesko/local/cabana/build_kokkos_icpx/install/include -I/home/pvelesko -I/home/pvelesko/local/intel/x86/include -I/home/pvelesko/local/kokkos_mainline/build_icpx/install/include -I/home/pvelesko/local/cabana/build_kokkos_icpx/install/include -I/home/pvelesko /home/pvelesko/XGC-Devel/xgc_build -c -o /home/pvelesko/XGC-Devel/xgc_build/cpp_scatter.o cpp_scatter.cpp
In file included from cpp_species.hpp(4),
                 from cpp_transpose_send.hpp(4),
                 from cpp_scatter.cpp(5):
/home/pvelesko/local/cabana/build_kokkos_icpx/install/include/Cabana_DeepCopy.hpp(156): error: identifier "is_aosoa" is undefined
             typename std::enable_if<( is_aosoa<DstAoSoA>::value &&
`

**Comment by junghans** [comment]
@pvelesko couldn't you build Cabana with Spack as well?

**Comment by pvelesko** [comment]
@junghans I have never  used spack, I just found some modules named spack which gave me access to cmake. Either way, that is not a long-term solution. I'd like to figure out what is going on here.

**Comment by sslattery** [comment]
@pvelesko Do you include `Cabana_Core.hpp` or just individual header files?

**Comment by pvelesko** [comment]
`cpp/cpp_species.hpp:#include <Cabana_AoSoA.hpp>
cpp/cpp_species.hpp:#include <Cabana_DeepCopy.hpp>
`

**Comment by sslattery** [comment]
Those includes should be fine. Is it possible that an `AoSoA` isn't getting passed into the `deep_copy` function you are calling? Does the compiler tell you what the type of `DstAoSoA` is in the error output? Usually on a bad template deduction it will tell you what type you passed in.

**Comment by sslattery** [comment]
Also @pvelesko can you share the code that you are building?

**Comment by rfbird** [comment]
Everything building fine with `icpc`, I guess this is an `icpx` specific issue? We'll probably need a reproducer..

**Comment by pvelesko** [comment]
I filed another ticket for icpc. It doesn't build at all with icpc. And I
did enable c14 in kokkos.

**Comment by pvelesko** [comment]
Turns out there was an older version of Cabana in a different place on my system that was getting picked up when compiling the application but not Cabana itself. Sorry!
