### ISSUE TITLE
Automatically detect vector length from Kokkos arch configuration flag

### ISSUE THREAD

**Issue by sslattery** [ECP-copa/Cabana#29]
Currently we have sensible default vector lengths defined in our `PerformanceTraits` class for different memory spaces (e.g. 16 for CPU and 32 for GPU).

Kokkos configuration allows for the specification of an architecture flag from numerous choices (e.g. `Pascal60` for a P100 with compute capability 6.0 or `HSW` for Intel Haswell). We should be able to grab these flags, create an environment variable, and automatically set the vector length for the user by default. The user should still be able to override, however.

**Comment by sslattery** [comment]
In hindsight this would be a lot of hardware-specific tuning and our proxy apps have shown that there is not one good choice across all application types. Based on the amount of work to manage all architecture types and the fact that those might not be a good choice anyway I think it is better to have a sensible default for a given execution space as we have now rather than architecture type.

**Comment by rfbird** [comment]
We should have a chat about some of this stuff wrt some of the OMP Variant stuff (https://www.openmp.org/spec-html/5.0/openmpsu29.html) which Kokkos may add support for
