### ISSUE TITLE
Clang Format Inconsistencies 

### ISSUE THREAD

**Issue by rfbird** [ECP-copa/Cabana#297]
Currently we don't prescribe how pointers should be handled in the clang format file, and instead leave it to be inferred (via `DerivePointerAlignment`). This means: 

1. We have inconsistent formatting in the code; and 
2. It allows different versions of clang format to do different things (which is currently causing me issues, where my format disagrees with Travis). 

I propose we switch to specifying a value for `PointerAlignment`, and will make a PR. It looks like in the code currently we (mostly) do middle alignment for pointers and right alignment for references...

**Comment by sslattery** [comment]
Lets go with `left` for `PointerAlignment`
