### ISSUE TITLE
Recover peakflops benchmark

### ISSUE THREAD

**Issue by guangyechen** [ECP-copa/Cabana#30]
It appears like somehow the Cabana_peakflops benchmark has lost the performance, which should be recovered.

**Comment by sslattery** [comment]
Which aspect - the Slice variant?

**Comment by guangyechen** [comment]
Bob and I were looking at it yesterday, and none of them were able to reach peak.

**Comment by rfbird** [comment]
I'm definitely a bit confused by this, and will make time to look at it. Hopefully soon, but definitely before the release. If it turns out to be very complex, now the code is open source I can always ask some of my contacts at intel if they might be willing to donate us an hour

**Comment by guangyechen** [comment]
I have now recovers the peakflops on a haswell cpu for AoSoA Cast. We need to look into the other two: Slice Single Index, and Slice Struct/Array Index.

**Comment by sslattery** [comment]
@guangyechen If you believe this to be fixed can you close?

**Comment by sslattery** [comment]
@guangyechen can this be closed? If a remember we addressed this in a PR

**Comment by sslattery** [comment]
Ping @guangyechen @rfbird - can this be closed?

**Comment by rfbird** [comment]
It's my understanding that it can be, but @guangyechen  should probably have the final say

**Comment by guangyechen** [comment]
About one week ago, it looked like there are some conflict with the Cabana repo.

**Comment by sslattery** [comment]
@guangyechen what conflicts? How can we capture this in the CI so that they don't show up again?

**Comment by guangyechen** [comment]
@sslattery I think some simple ones like some file was not there anymore, which the makefile was looking for.

**Comment by guangyechen** [comment]
@sslattery I just went to the pull request page, it shows up there (towards the end):
https://github.com/ECP-copa/Cabana/pull/52

**Comment by sslattery** [comment]
Can you make a pull request that fixes this?

**Comment by sslattery** [comment]
oh yeah you will just need to rebase when ready and resolve conflicts

**Comment by guangyechen** [comment]
Yes. That's likely all it is. I'd like to add the new simd_parallel_for in the tests, which should be simple (or we can do it later). I need to find the time to do this, but am currently busy with debugging the minipic.

**Comment by sslattery** [comment]
Does #111 close this @guangyechen @rfbird ?

**Comment by guangyechen** [comment]
No.  #111  only deals with Fortran examples.

**Comment by sslattery** [comment]
Oh yeah sorry - mean #52

**Comment by guangyechen** [comment]
I don't know if it is going to close (the current state is that not all tests are passed) it but it is certainly related.

**Comment by streeve** [comment]
Did #152 resolve this issue?

**Comment by sslattery** [comment]
@guangyechen Can we close this?

**Comment by sslattery** [comment]
Closing - resolve by #152
