### ISSUE TITLE
MPI_Allreduce for Cabana AoSoA

### ISSUE THREAD

**Issue by iplasma** [ECP-copa/Cabana#322]
Hi,

I wonder if there is support of MPI_Allreduce type operation for data stored in Cabana AoSoA layout? If not, what would be an alternative approach?

Thanks!

**Comment by sslattery** [comment]
Are you interested in an `MPI_Allreduce` on a specific data member of an AoSoA? The straightforward way to do that would be a `Kokkos::parallel_reduce` on the local element (or group of elements) and then to take the result of the local reduce and pass that the `MPI_Allreduce` for the global reduction. Will that work for your purposes?

**Comment by iplasma** [comment]
I have AoSoA on each MPI rank and there are several data members in the AoSoA. I would like to reduce the data on all  ranks for each data member (not a global reduce of all data members). From the [unmanaged AoSoA example](https://github.com/ECP-copa/Cabana/blob/master/example/tutorial/04_aosoa_advanced_unmanaged/advanced_aosoa_unmanaged.cpp), I was thinking to define MPI datatype corresponding to the AoSoA. Maybe there is a better solution?

**Comment by sslattery** [comment]
Ah OK so this is a per-element reduction. So then the number of AoSoA elements is equal on all MPI ranks (e.g. AoSoA.size()) is equivalent.

**Comment by iplasma** [comment]
Yes, number of AoSoA elements is equal on all ranks. My AoAoA is like this,

```
using meshfield_t = Cabana::MemberTypes<
    double,  // FLD1,
    double,  // FLD2,
    double   // FLD3,
    >;

using fields = Cabana::AoSoA<meshfield_t, HostSpace>;
fields mesh_flds;
mesh_flds.resize(size);


```

So each rank owns a (same) mesh with several fields defined on it. I would like to do an all_reduce so each field on all ranks will be summed on the mesh. Sorry for the confusion. Perhaps Cajita is intended for this, but I don't know that will make the implementation simpler.

**Comment by sslattery** [comment]
If your grid is a logically structured Cartesian grid then Cajita will be the way to go as it will have all of the array operations you are looking for I suspect. If your mesh is unstructured then it is reasonable to try using an AoSoA for the mesh fields in conjunction with some kind of connectivity map.

If the later is your situation one thing you could do (although less efficient) is call `Allreduce` 3 times - one on a `slice` of each field member. The other way to do it is use `Allreduce` once where `count` is 3 times the size of the AoSoA and you manually unroll the AoSoA into the MPI buffer. You could also try writing your own MPI data type for a more efficient reduction.

**Comment by sslattery** [comment]
@iplasma Do you need any more help?

**Comment by streeve** [comment]
Closing - this has been open for a year..
