### ISSUE TITLE
CartesianGrid returns incorrect indicies for boundary points

### ISSUE THREAD

**Issue by ejm930** [ECP-copa/Cabana#333]
In `Cabana_CartesianGrid.hpp` [locatePoint](https://github.com/ECP-copa/Cabana/blob/d46804f0e002be4d9f7740fc94a34c4ff1fe6aa3/core/src/impl/Cabana_CartesianGrid.hpp#L101)  returns incorrect i,j,k indices when a point is on the boundary. This can lead to incorrect cardinal indices. For example a 2x2x2 grid of cell size 1x1x1 with` locatePoint(2.0, 2.0, 2.0, ic, jc, kc) `sets (ic = 2, jc = 2, kc = 2). This behaviour is only correct if we assume particles can be in the domain, but not on the boundary. The use of `floor` [cellsBetween](https://github.com/ECP-copa/Cabana/blob/d46804f0e002be4d9f7740fc94a34c4ff1fe6aa3/core/src/impl/Cabana_CartesianGrid.hpp#L148) leads to this off by one error.

**Comment by sslattery** [comment]
Thanks for reporting! We will work on a fix and push.

**Comment by ejm930** [comment]
No problem! I submitted a pull request with a quick fix.
