### ISSUE TITLE
Cajita documentation and examples

### ISSUE THREAD

**Issue by streeve** [ECP-copa/Cabana#352]
General issue for keeping track of where documentation needs to be updated for Cajita:

- [x] Doxygen undocumented classes/functions

Tutorial & wiki
- [x] 01-04 Initial (#391)
- [x] 05 IndexSpace @streeve
- [x] 06 LocalGrid @streeve 
- [x] 07 LocalMesh @streeve
- [x] 08 Array @streeve 
- [x] 09 Parallel @streeve 
- [x] 11 Structured solver @kwitaechong 
- [x] 12 Halo @kwitaechong 
- [x] 14 Splines @abisner 
- [x] 15 Interpolation @abisner

**Comment by XzzX** [comment]
https://github.com/ECP-copa/Cabana/wiki/Cajita-Interpolation is also not really useful at the moment.
