### ISSUE TITLE
Device neighbor iterating

### ISSUE THREAD

**Issue by j8asic** [ECP-copa/Cabana#357]
`neighbor_parallel_for` is a host function that asks for a functor, and thus enforcing that the whole kernel equals to neighbour interaction functor. 

In addition to `neighbor_parallel_for` I'd suggest a function for on-device iterating, e.g. called `neighbor_for`, that calls some device functor. This is far more common in my case then interaction-only kernels.

I don't know your coding style, but `neighbor_for` can even be in a struct containing all vars if you don't like the syntax that is passing template params and variables in a kernel.

```
template< ... >
struct NeighborIterating {
// NeighborListType& list;     ... other vars ...     ... constructor ...

template<class F>
KOKKOS_INLINE_FUNCTION void neighbor_for(index_type i, F functor) const {
  for ( index_type n = 0;  n < numNeighbor( list, i ); ++n )
    functor(getNeighbor(list, i, n));
}

};
```

Or simply I can just call by myself `numNeighbor` & `getNeighbor` inside the kernel :) ...

**Comment by sslattery** [comment]
@j8asic To summarize - you want a helper function to serialize the loop over neighbors and just pass the neighbor index to the user functor such that you only operate on the user functor? Is this part of any larger reduction? I'm curious if you will ever want the neighbor loop to be threaded.

@streeve I think we can do this now by choosing the serial neighbor loop and simply ignoring the `i` index correct?

**Comment by j8asic** [comment]
Thanks for the quick response. Good question, forgot to mention that for the above helper function I did not thought about any reductions. Simple non-threaded iteration allowed in a user kernel.

**Comment by streeve** [comment]
I also have cases where I don't need to do everything in the inner most loop (and currently do anyway), so I could also use this capability. The nice thing is that this `neighbor_for` concept would fuse these non-neighbor and neighbor kernels.

Maybe it would be good to have new overloads or an optional non-neighbor functor argument for the `neighbor_parallel_for`. Or we could start with this and improve the code reuse later

**Comment by sslattery** [comment]
I'm open to either design you have suggested. I think this is really a new kind of parallelism so some kind of tag might be a nice way to trigger this pattern as a specialization of `neighbor_parallel_for`

**Comment by streeve** [comment]
@j8asic let me know if what I put together doesn't work for your use case - I'm happy to add you to our slack channel for more discussion

**Comment by j8asic** [comment]
@streeve thanks. This is very clean and good. It captures about half cases that I have. Other cases need to do something with interaction result immediately after the neighbour iteration. And there may be kernels that would like to skip iteration in some cases. So instead of adding a parent-host function for all combinations, I had in mind adding a simplest wrapper for on-device iterating, not putting the constraints on executing the central kernel for the user. Something like this (writing by heart, sorry about the syntax):

```
template <class IndexType, class NeighborListType, class NeighborFunctorType>
KOKKOS_INLINE void neighbor_for(IndexType i, const NeighborListType& list, const NeighborFunctorType& neighbor_functor)
{
    using neighbor_list_traits = NeighborList<NeighborListType>;

    for (index_type n = 0; n < neighbor_list_traits::numNeighbor(list, i); ++n)
        neighbor_functor(static_cast<IndexType>(neighbor_list_traits::getNeighbor(list, i, n)));

}

// usage:

auto my_kernel = KOKKOS_LAMBDA(const int i) {

    int something = 0; // do something with i

    neighbor_for(i, list, [&](const int j) {
        something++; // do interaction
    });

    something *= 10; // finalize interaction and save result
};
```

What do you think about this? This give the user a lot of control, and stays clean. If I am thinking things incorrectly, please correct me. (I know I can do this manually like noted in the first post :)

**Comment by streeve** [comment]
@j8asic I finally fixed my threading bug on the new version (that basically matches your example for serial). Let me know your thoughts

**Comment by j8asic** [comment]
Thanks, I think now all cases can be covered.

Just a question: do you prefer to have arguments after the functor or it should be the last one (for inline-lambdas readability)? Asking since in Kokkos parallel_for this is the case, but for reduce it isn't.

**Comment by streeve** [comment]
I don't have a strong opinion on ordering, but we've generally tried to match Kokkos style in cases where we're directly extending and then add other parameters after. So now I'm just trying to match the new inline functions to the other neighbor parallel functions

**Comment by sslattery** [comment]
I agree with both you you guys here. In hindsight functors at the end would help with readability for inline definitions. But what @streeve has written here directly follows our previous `neighbor_parallel_for` structure which makes sense as well. With that said I think the code in #360 is looking good.
