### ISSUE TITLE
Change Default Compiler Flags to favor aggressive optimization

### ISSUE THREAD

**Issue by rfbird** [ECP-copa/Cabana#37]
As per some previous offline discussion, I think it might be good to do some combination of the following:

1) Make the default build type `release` (which likely gives `-O3`)
2) Consider adding compiler flags to add platform specific code (`-march=native`, `-xHost` etc)

@junghans  has already done this for another project, so it should be fairly straight forward to port over

**Comment by junghans** [comment]
@sslattery any other wishes?

**Comment by sslattery** [comment]
I agree on the platform specific flags. Kokkos already does this through their architecture options - can we grab those flags as well?
