### ISSUE TITLE
Kokkos version requirements

### ISSUE THREAD

**Issue by streeve** [ECP-copa/Cabana#397]
This issue is intended for discussion of Kokkos version requirements: how aggressive we can/should we be in order to use new Kokkos features while not negatively impacting downstream applications 

We currently require Kokkos 3.2, where some features of 3.4 would be useful, for example

**Comment by streeve** [comment]
@ascheinb can you let us know what you think from the XGC side? Or tag others as you like

**Comment by dalg24** [comment]
Not yet but it is probably a good idea to prepare for this as well.  Kokkos plans on requiring C++17 at the end of the calendar year.

**Comment by streeve** [comment]
From internal discussions we will be switching to a strategy of supporting the two most recent Kokkos releases. This will be in effect once #472 is merged (supporting 3.4 and 3.5). Support for Kokkos 3.4 will last until 3.6 is released

**Comment by streeve** [comment]
Closing now that #472 was merged
