### ISSUE TITLE
Performance regression benchmarks

### ISSUE THREAD

**Issue by sslattery** [ECP-copa/Cabana#4]
Capturing outcome of discussion: 

* [x]  A peak flops benchmark (ala GY)
* [x]  BW bound kernel test
* [x]  A demonstration of the performance implications of kernel fusion/fission
* [x]  A demonstration of the performance implications of using multiple lists to track particle properties
* [x]  An MPM like kernel
* [x]  A VPIC like PIC kernel 
* [x] Communication halo exchange/redistribution
* [x] Neighbor list generation

**Comment by guangyechen** [comment]
Implied I guess also includes testing the basic AOSOA/SOA/AOS with different kernels.

**Comment by sslattery** [comment]
@guangyechen @rfbird can you link this issue tor relevant PRs you are working on?

**Comment by sslattery** [comment]
@rfbird Lets clean this one up. 

We have both a VPIC-like proxy (CabanaPIC) and an MPM proxy (ExaMPM) in the project space. @streeve has infrastructure to look at performance as a function of multiple particle property lists. The ExaMPM work has a recent publication as well that shows kernel fusion improving results. 

Only thing not covered in that list is a bandwidth-bound kernel. Do we have a demo for that? Also can we count these other cases as sufficient to tick the boxes here?

**Comment by streeve** [comment]
To this end, I recently added a wiki page pointing for the [proxy apps](https://github.com/ECP-copa/Cabana/wiki/Proxy-Apps) - maybe we could add a bit more there about features of note like these.

Is it enough to align the [wiki benchmarks](https://github.com/ECP-copa/Cabana/wiki/Benchmarks) and the performance tests?

**Comment by rfbird** [comment]
I agree this needs to be tidied up/put to bed. Which bits do we still consider a priority?

**Comment by sslattery** [comment]
> To this end, I recently added a wiki page pointing for the [proxy apps](https://github.com/ECP-copa/Cabana/wiki/Proxy-Apps) - maybe we could add a bit more there about features of note like these.
> 
> Is it enough to align the [wiki benchmarks](https://github.com/ECP-copa/Cabana/wiki/Benchmarks) and the performance tests?

Nice! Yeah I think we need to just align those in the wiki and we are fine. 

@rfbird I think the only thing we are missing is bandwidth. I think we have that stream test but does that make sense in the context of what we are trying to achieve?

**Comment by sslattery** [comment]
Actually looks like bandwidth is covered here: https://github.com/ECP-copa/Cabana/wiki/Benchmarks

So I'll say we are good on this unless there are any objections

**Comment by rfbird** [comment]
Yea, I think we have everything we need for now. I'm very happy to add anything we need, but we can deal with that as it comes up?

I might look at adding a gather benchmark as that's where I think our performance falls down

**Comment by sslattery** [comment]
sounds good - lets add benchmarks as we make them
