### ISSUE TITLE
Atomic access required in neighbor_parallel_for_example.cpp?

### ISSUE THREAD

**Issue by XzzX** [ECP-copa/Cabana#401]
I am currently working through the tutorials. They are very clear and the code base is really nice. :+1: 

While reading through https://github.com/ECP-copa/Cabana/blob/master/example/tutorial/10_neighbor_parallel_for/neighbor_parallel_for_example.cpp I stumbled over a potential race condition. For `Cabana::TeamOpTag()` parallelization is done over particles and neighbors, right? This should result in a race condition here https://github.com/ECP-copa/Cabana/blob/master/example/tutorial/10_neighbor_parallel_for/neighbor_parallel_for_example.cpp#L124-L127, since access to `slice_i( i )` is not atomic. Did I miss something?

**Comment by sslattery** [comment]
@XzzX Nice catch! We have an update coming.

**Comment by streeve** [comment]
Thanks again for finding this and letting us know. I completely missed that when I wrote this example
