### ISSUE TITLE
something wrong with the first template parameter of VerletList

### ISSUE THREAD

**Issue by XzzX** [ECP-copa/Cabana#405]
According to the documentation the first template parameter of `VerletList` should be a `DeviceType`
https://github.com/ECP-copa/Cabana/blob/d6505da281b23344952aec075905f21f759f5a8c/core/src/Cabana_VerletList.hpp#L611-L630

However, the example uses a `MemoryType`
https://github.com/ECP-copa/Cabana/blob/d6505da281b23344952aec075905f21f759f5a8c/example/core_tutorial/10_neighbor_parallel_for/neighbor_parallel_for_example.cpp#L112

and in fact passing a `DeviceType` will result in a `static_assert` during `neighbor_parallel_for`.

**Comment by sslattery** [comment]
@streeve Can you take a look at this one? We admittedly need to transition to memory spaces instead of device types for object templates but have not done this yet.

**Comment by streeve** [comment]
Thanks again for pointing out our bugs @XzzX. We should be able to merge the fix soon
