### ISSUE TITLE
wiki entry for slices is outdated

### ISSUE THREAD

**Issue by XzzX** [ECP-copa/Cabana#408]
https://github.com/ECP-copa/Cabana/wiki/Slice

`auto slice_A = aosoa.slice<A>();` does not work anymore. I think this is replaced by `auto slice_A = Cabana::slice<A>(aosoa);`.

Multiple occurrences.

**Comment by streeve** [comment]
Thanks. I fixed throughout the wiki, but reopen if I missed something
