### ISSUE TITLE
Missing work_tag support for neighbor_parallel_for and neighbor_parallel_reduce

### ISSUE THREAD

**Issue by XzzX** [ECP-copa/Cabana#414]
`Cabana::neighbor_parallel_for` and `Cabana::neighbor_parallel_reduce` do not support `function name tags`. 

The internal lambda has no `work_tag`
https://github.com/ECP-copa/Cabana/blob/575a692f1212a6be4059023ea75a81c25852f5c0/core/src/Cabana_Parallel.hpp#L243

However, this lambda is called via `Kokkos::parallel_for` which passes the `work_tag` as the first argument.
https://github.com/ECP-copa/Cabana/blob/575a692f1212a6be4059023ea75a81c25852f5c0/core/src/Cabana_Parallel.hpp#L253

**Comment by sslattery** [comment]
Good catch! We do in fact support work tags but we have no examples or unit tests of this. We will get this added. Thanks!
