### ISSUE TITLE
OpenMP support on Clang + ubuntu:rolling

### ISSUE THREAD

**Issue by sfogerty** [ECP-copa/Cabana#465]
The Kokkos build does a test compilation to ensure OpenMP is supported by the compiler. For Clang, this is done with:

```
  TRY_COMPILE(CLANG_HAS_OMP
    ${KOKKOS_TOP_BUILD_DIR}/corner_cases
    ${KOKKOS_SOURCE_DIR}/cmake/compile_tests/clang_omp.cpp
    COMPILE_DEFINITIONS -fopenmp=libomp
    LINK_LIBRARIES -fopenmp=libomp
  )
```

In our CI for Clang++, ubuntu:rolling, this test fails. Kokkos gives the error:
```
CMake Error at cmake/kokkos_corner_cases.cmake:20 (MESSAGE):
  Clang failed OpenMP check.  You have requested -DKokkos_ENABLE_OPENMP=ON,
  but the Clang compiler does not appear to have been built with OpenMP
  support
```

**Comment by sfogerty** [comment]
I'm not sure if these errors are something we can fix on our end, or something wrong in ubuntu:rolling?

Should we just remove this test for now, or at least allow it to fail?

@junghans @dalg any thoughts?

**Comment by junghans** [comment]
Hopefully that will fix it https://github.com/kokkos/ci-containers/pull/25

**Comment by sfogerty** [comment]
Thanks for digging into this @junghans
