### ISSUE TITLE
support for unstructured mesh with non-uniform particle distribution

### ISSUE THREAD

**Issue by cwsmith** [ECP-copa/Cabana#48]
Hello,
We are working on plasma physics codes that use an unstructured mesh and are looking for particle data structures that support:
1. grouping particles by the elements they are positioned within,
2. a range of particle distributions; e.g., uniform, Gaussian, scale-free/exponential,
3. coalesced memory access for SIMD/SIMT particle 'push' operations,
4. sufficient parallelism for particle push operations,
5. changing the element a particle is associated with without having to rebuild the entire particle structure, and 
6. adding particles to the domain without having to rebuild the entire particle structure.

We want to group the particles by mesh element to minimize the amount of mesh field and topology data replicated and accessed during 'push' operations (new particle positions, scatter, and gather).  For example, with particles grouped by element, all of the particles within an element could access the same, relatively small, fast memory that stores the field data associated the mesh vertices of the element.

From what I can tell, Cabana supports items 3 through 5.  Particles could be added to the domain, item 6, by calling the AoSoA constructor with a larger number of tuples beyond what is initially needed; the amount of reserve capacity created would be application dependent.

To support grouping by element, item 1, and non-uniform particle distributions, item 2, I can think of a few approaches:

A. We could define a tuple that includes the id of the parent mesh element and then use an AoSoA sort by element id.  Relative to the particle operations that compute new particle positions for element fields, scatter, and gather, the sort seems to be a non-trivial expense.

B. We could avoid sorting, and the memory use of each tuple including a mesh element id, by storing the first and last particle/tuple that belongs to each element.  Given an initial distribution of particles, we could allocate a larger than necessary set of tuples, and reserve spare tuples at the end of each elements range of active tuples.  When a particle changes element we mark the source tuple as spare and write the data to the first spare tuple in the elements range.  When there are no spare tuples for a given element, the structure could either be rebuilt with additional capacity, or the spare tuples redistributed (via sorting) to place them in the range of the elements that require them.

C. Define variable length SoAs for each element in the AoSoAs.  This would incorporate the ideas of approach B, but without the need to track the first and last tuple for each element.  I suspect this approach is not readily possible with Cabana. 

Any feedback is appreciated.

Thank-you,
Cameron

**Comment by sslattery** [comment]
Hi Cameron - thanks for the interest. 

I think items 1 and 3-6 are all currently doable with the library although a few of the operations may not be as optimal as they could be without further refinement. Number 2 should be relatively easy to implement in your code base with the existing parallel infrastructure.

For item 6, also consider the use of the `reserve` and `resize` functions in the `AoSoA` interface - this data structure will only reallocation and copy if the capacity is increased.

Both myself and @rfbird have been thinking quite about about how to carefully arrange particles for mesh interactions in PIC-like codes so our efforts are very much aligned with yours. We have a number of PIC codes involved in the project so we would definitely benefit from further feedback from your project as well. With regards to your suggestions on how to handle this:

A) I agree sorting is expensive here but there are some new algorithms that do a "partial sort" where only the particle's coordinates are sorted and the remaining data is sorted "in-place" upon access. This seems to be a reasonable approach for the grid/particle interaction where vectorization will be difficult without substantial local scatter/gather operations.

B) This seems like a reasonable approach - I would like to explore this further. The AoSoA data structure has everything needed to do this.

C) This is possible but tricky given our compile-time vector length in the SoA data structures and therefore would require some refactoring. We have seen some potential performance benefits to this compile-time approach and it permits allocation of a single data block. There may be future architectures where a variable vector length would be useful so this one is definitely consideration for our to-do list in the future.

With regards to general usage of Cabana for PIC work, you can look for a general set of MPI tools to be added at the end of this quarter in a 0.2 release and a structured grid particle/grid gather/scatter capability next quarter in a 0.3 release. One of our partners uses unstructured grids so we will tackle the particle-to-grid and grid-to-particle operation for those after the structured work is complete.

We would be happy to set up a call to discuss further.

Stuart

**Comment by cwsmith** [comment]
As discussed in the telecon and the deepdive meeting, we will pursue option B.
