### ISSUE TITLE
documentation/examples for interfaces to third-party libraries

### ISSUE THREAD

**Issue by XzzX** [ECP-copa/Cabana#496]
It is hard to figure out how to use the interfaces for `heFFTe`, `HYPRE`, `ALL` and `ArborX`. I think the best sources are currently the unit tests. Can you add short usage examples and/or a dedicated wiki page for these interfaces?

**Comment by streeve** [comment]
For each dependency, let's add an in-repo example and add to/update the wiki page (linked from https://github.com/ECP-copa/Cabana/wiki/Programming-Guide):

- @sfogerty heFFTe
- @sslattery hypre
- @aetx ALL
- I'll do ArborX (very little to be done anyway)
