### ISSUE TITLE
add non CPU backend to the CI

### ISSUE THREAD

**Issue by XzzX** [ECP-copa/Cabana#497]
Currently all CI jobs target CPU backends of Kokkos. Since GitHub runners do not have GPUs a full GPU CI is not possible this way. However, just compiling with, for example, `nvcc` catches something like `calling host function from device function`. 

One of the premade docker containers from Nvidia could do the job.

**Comment by dalg24** [comment]
This is not accurate
https://github.com/ECP-copa/Cabana/blob/1b3bdc789e990e676438690e8516fb6c02cd6816/.jenkins#L15
https://github.com/ECP-copa/Cabana/blob/1b3bdc789e990e676438690e8516fb6c02cd6816/.jenkins#L55
https://github.com/ECP-copa/Cabana/blob/1b3bdc789e990e676438690e8516fb6c02cd6816/.jenkins#L95

**Comment by XzzX** [comment]
Ok, my mistake. I did not see the jenkins CI.
