### ISSUE TITLE
Hide format target if built as a subproject?

### ISSUE THREAD

**Issue by XzzX** [ECP-copa/Cabana#498]
I include two third-party projects in my library via `FetchContent` and both expose a `format` target. This collision makes cmake crash. The problem would also arise if you use git submodules.

What do you think about wrapping the format target with something similar to
https://cliutils.gitlab.io/modern-cmake/chapters/testing.html?
If you want, I can provide a patch.

https://github.com/ECP-copa/Cabana/blob/1b3bdc789e990e676438690e8516fb6c02cd6816/CMakeLists.txt#L242-L250

**Comment by dalg24** [comment]
> https://cliutils.gitlab.io/modern-cmake/chapters/testing.html

I am not able to access.
