### ISSUE TITLE
Check if a header is not included in src/CMakeLists.txt by accident

### ISSUE THREAD

**Issue by sslattery** [ECP-copa/Cabana#55]
#43 Changed the build so that `GLOB` is no longer used to allow for enabling specific components based on optional TPL availability. We want to know if a new header is accidentally not added by a developer where, if any errors occur. Do they occur when building tests or only when someone links against an install and finds it is missing.

**Comment by junghans** [comment]
We could do a `GLOB` can print a developer only message with `message(AUTHOR_WARNING ..)` if a header isn't getting installed.

**Comment by sslattery** [comment]
@junghans @dalg24 is there a reasonable way to do this or is this a priority? Otherwise I would like to backlog due to inactivity

**Comment by dalg24** [comment]
I don't think this is worth investing much time in solving this.

**Comment by sslattery** [comment]
OK - will backlog then due to other priorities.
