### ISSUE TITLE
Cajita heffte glue code failing with gcc 11/cuda 11.6 or 11.7

### ISSUE THREAD

**Issue by patrickb314** [ECP-copa/Cabana#561]
Not clear if this is a Cabana issue or not - A kernel launch for a parallel for loop in the heffte glue code fails when compiled with gcc 11/cuda 11.6 or 11.7, but suceeds when compiled with gcc 10.

**Comment by streeve** [comment]
This is what I hit when trying to reproduce:
```
[  3%] Building NVCC (Device) object CMakeFiles/Heffte.dir/src/Heffte_generated_heffte_backend_cuda.cu.o
In file included from /sw/summit/cuda/11.0.3/include/cuda_runtime.h:83,
                 from <command-line>:
/sw/summit/cuda/11.0.3/include/crt/host_config.h:139:2: error: #error -- unsupported GNU version! gcc versions later than 9 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
 ```
 
I don't think we can do anything there

**Comment by patrickb314** [comment]
NVCC from cuda 11.6 on is supposed to be compatible with gcc 11; 11.0.3 doesn't support  gcc 11, however.

**Comment by streeve** [comment]
I'll have to look for another system to try on

**Comment by streeve** [comment]
@mkstoyanov have you tested with this combination?

**Comment by mkstoyanov** [comment]
My workstation has Ubuntu 22.04 which comes with CUDA 11.7 and gcc-11.2.0 and openMPI 4.1.4, heFFTe works

patrickb314 mentioned it is in the glue code, I'm assuming Kokkos. Could there be an issue with that?

**Comment by patrickb314** [comment]
Correct - it’s in the Cajita glue code to heffte in a Kokkos parallel_for that’s it’s dying with an invalid kernel launch error, not in heffte itself.

From: Miroslav Stoyanov ***@***.***>
Date: Tuesday, August 9, 2022 at 3:59 PM
To: ECP-copa/Cabana ***@***.***>
Cc: Patrick Bridges ***@***.***>, Author ***@***.***>
Subject: Re: [ECP-copa/Cabana] Cajita heffte glue code failing with gcc 11/cuda 11.6 or 11.7 (Issue #561)

My workstation has Ubuntu 22.04 which comes with CUDA 11.7 and gcc-11.2.0 and openMPI 4.1.4, heFFTe works

patrickb314 mentioned it is in the glue code, I'm assuming Kokkos. Could there be an issue with that?

**Comment by streeve** [comment]
Must be the Kokkos version then - can you try Kokkos 3.2 and Kokkos 3.4?

**Comment by sfogerty** [comment]
@streeve Still working with both Kokkos 3.2 and Kokkos 3.4 so I'm not sure about the source of the issue

**Comment by patrickb314** [comment]
It could also be a problem in my code that’s calling Cajita/Kokkos where that glue code is getting inlined. I’m happy to give access to the repo to anyone that wants to look at it.

From: Sam Reeve ***@***.***>
Date: Wednesday, August 10, 2022 at 12:32 PM
To: ECP-copa/Cabana ***@***.***>
Cc: Patrick Bridges ***@***.***>, Author ***@***.***>
Subject: Re: [ECP-copa/Cabana] Cajita heffte glue code failing with gcc 11/cuda 11.6 or 11.7 (Issue #561)

Must be the Kokkos version then - can you try Kokkos 3.2 and Kokkos 3.4?

**Comment by patrickb314** [comment]
Sent invites to the current repository - relevant testcase is on the develop branch. I'm going to go ahead and close this issue and move the discussion to that repository since this doesn't seem to be, at least for now, a Cabana issue.
