### ISSUE TITLE
runtime error: Calling simd_parallel_for in an 'if constexpr'

### ISSUE THREAD

**Issue by NMiklu** [ECP-copa/Cabana#614]
Runtime error when executing consecutive 'if constexpr'.

**Example code:** https://gist.github.com/144e45d6f77ae677e862f962264c5066.git

A functionally similar code snippet (excluding Cabana) compiles here: https://godbolt.org/z/Gh39hbd1W

Kokkos: fb3d754f58288d5c630fedaaa14a0a027253f209
Cabana: 452a2788b3dffebfb1ce20e4265a7bb7c737e9e9
gcc/10.1.0
cuda/11.4

Error:
`terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaFuncGetAttributes(&attr, func) error( cudaErrorInvalidDeviceFunction): invalid device function /users/ ... / ... /build-kokkos-cranium-cuda/install/include/Cuda/Kokkos_Cuda_KernelLaunch.hpp:140
Aborted (core dumped)`

**Comment by streeve** [comment]
I was able to reproduce the error with just Kokkos - @dalg24 is this allowed in a Kokkos lambda?

**Comment by masterleinad** [comment]
Any chance that you are using a captured `constexpr` variable the first time in `if constexpr`? That's known to be problematic.

**Comment by crtrott** [comment]
The lambda is not capturing anything so its not mismatched captures.

**Comment by cwsmith** [comment]
Thank you.  For the record, here is our kokkos reproducer:
https://gist.github.com/NMiklu/0374aa86680e729ff1fa952526df8dcd

**Comment by crtrott** [comment]
Non Kokkos reproducer: 
```c++
#include <cuda_runtime.h>
#include <stdio.h>
#include <iostream>
#include <typeinfo>

template<class Lambda>
__global__ void kernel(const Lambda l) {
  l(0);
}

template <const int theta> void testLogic() {
  int policy = 1;
  if constexpr (theta == 1) {
    auto lambda = [=]__host__ __device__ (const int) { printf("L1\n"); };
    //Kokkos::parallel_for(1, lambda);
    kernel<<<1,1>>>(lambda);
    auto error1 = cudaDeviceSynchronize();
    auto error2 = cudaGetLastError();
    std::cout << error1 << " " << error2 << " [ "<< typeid(lambda).name() << " ]" << std::endl;
  }
  if constexpr (theta == 2) {
    auto lambda = [=]__host__ __device__ (const int) { printf("L2"); };
    //Kokkos::parallel_for(1, lambda);
    kernel<<<1,1>>>(lambda);
    auto error1 = cudaDeviceSynchronize();
    auto error2 = cudaGetLastError();
    std::cout << error1 << " " << error2 << " [ "<< typeid(lambda).name() << " ]" << std::endl;
  }
  if constexpr (theta == 3) {
    auto lambda = [=]__host__ __device__ (const int) { printf("L3"); };
    //Kokkos::parallel_for(1, lambda);
    kernel<<<1,1>>>(lambda);
    auto error1 = cudaDeviceSynchronize();
    auto error2 = cudaGetLastError();
    std::cout << error1 << " " << error2 << " [ "<< typeid(lambda).name() << " ]" << std::endl;
  }
}

int main(int argc, char *argv[]) {
  int num_tuples = (argc < 2) ? (1000) : (atoi(argv[1]));

  testLogic<1>();
  testLogic<2>();
  testLogic<3>();
  return 0;
}
```

Compile with `nvcc -x cu main.cpp -std=c++17 -arch=sm_70 --extended-lambda`

Output: 
```
L1
0 0 [ 18__nv_hdl_wrapper_tILb0ELb0E11__nv_dl_tagIPFvvEXadL_Z9testLogicILi1EEvvEELj1EEFviEJEE ]
0 98 [ 18__nv_hdl_wrapper_tILb0ELb0E11__nv_dl_tagIPFvvEXadL_Z9testLogicILi2EEvvEELj2EEFviEJEE ]
0 98 [ 18__nv_hdl_wrapper_tILb0ELb0E11__nv_dl_tagIPFvvEXadL_Z9testLogicILi3EEvvEELj3EEFviEJEE ]
```

**Comment by crtrott** [comment]
Did you check the CUDA lambda restrictions if this is listed?

**Comment by cwsmith** [comment]
Not yet.  There is some mention of constexpr here but we'll have to read into this a bit more: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#extended-lambda-restrictions

**Comment by cwsmith** [comment]
from kokkos slack: NVBug 4089329 filed

**Comment by cwsmith** [comment]
Update from slack: this is a known issue and is resolve in nvcc >= 12.0.
