### ISSUE TITLE
How to compute interactions when dealing with more than one set of particles?

### ISSUE THREAD

**Issue by dineshadepu** [ECP-copa/Cabana#639]
Hi,

I am trying to write a code, where I am dealing with more than two sets of particles. In `SPH`, to simulate a dam breaking example, we handle the boundaries with three layers of particles. Those particles need not be computing the rate of change of density (continuity) and momentum equations, however, we need to compute the pressure on those boundary particles due to the interaction with the `fluid` particles. In order to simplify this kind of computing algorithm, we can divide given simulation into `fluid` and `boundary` particles, and compute only required equations on each set of particles will save lot of computational time. As a reference, please see the following figure:

![1](https://github.com/ECP-copa/Cabana/assets/13584458/f3900266-de7d-49d4-bd8b-c38ce1ab5ab7)

```cpp
#include <math.h>

#include <Kokkos_Core.hpp>
#include <Cabana_Core.hpp>


/*
  Setup the datatypes for positions, velocity
*/
const int MaxNoContacts = 10;
using CabanaDouble3DataType = Cabana::MemberTypes<double[3]>;
using CabanaDoubleDataType = Cabana::MemberTypes<double>;
using CabanaIntDataType = Cabana::MemberTypes<int>;

const int VectorLength = 4;
using MemorySpace = Kokkos::HostSpace;
using ExecutionSpace = Kokkos::DefaultHostExecutionSpace;
using DeviceType = Kokkos::Device<ExecutionSpace, MemorySpace>;

using AoSoA_int = Cabana::AoSoA<CabanaIntDataType, DeviceType, VectorLength>;
using AoSoA_double = Cabana::AoSoA<CabanaDoubleDataType, DeviceType, VectorLength>;
using AoSoA_double3 = Cabana::AoSoA<CabanaDouble3DataType, DeviceType, VectorLength>;

void compute_force(auto * force_dst,
		   auto * position_dst,
		   auto * mass_dst,
		   auto * position_source,
		   auto * mass_source,
		   auto * verlet_list_source){
  auto first_neighbor_kernel = KOKKOS_LAMBDA( const int i, const int j )
    {
      const double mass_i = *mass_dst( i );
      const double mass_j = *mass_source( j );

      const double x_i = *position_dst( i, 0 );
      const double y_i = *position_dst( i, 1 );
      const double z_i = *position_dst( i, 2 );

      const double x_j = *position_source( j, 0 );
      const double y_j = *position_source( j, 1 );
      const double z_j = *position_source( j, 2 );

      const double dx = x_i - x_j
      const double dy = y_i - y_j
      const double dz = z_i - z_j

      const double rsq = dx * dx + dy * dy + dz * dz;
      const double r = sqrt(rsq);

      if (r < 0.1){
	*force_dst( i, 0 ) += 1e5 * r;
	*force_dst( i, 1 ) += 1e5 * r;
	*force_dst( i, 2 ) += 1e5 * r;
      }
    }


  Kokkos::RangePolicy<ExecutionSpace> policy( 0, *position_dst.size() );


  Cabana::neighbor_parallel_for( policy,
				 first_neighbor_kernel,
				 verlet_list_source,
				 Cabana::FirstNeighborsTag(),
				 Cabana::SerialOpTag(),
				 "normal_force_loop" );
  Kokkos::fence();

}

void DEM_run(){
  std::cout << "Cabana Verlet Neighbor List Example\n" << std::endl;

  // =====================================================
  // fluid particles or first set of particles (set 1)
  // =====================================================
  int num_tuple_1 = 40;

  // AoSoA
  AoSoA_int id_1_aosoa( "id_1", num_tuple_1 );
  AoSoA_double mass_1_aosoa( "mass_1", num_tuple_1 );
  AoSoA_double3 position_1_aosoa( "position_1", num_tuple_1 );
  AoSoA_double3 force_1_aosoa( "force_1", num_tuple_1 );

  // Slices
  auto id_1 =  Cabana::slice<0>( id_1_aosoa );
  auto mass_1 = Cabana::slice<0>( mass_1_aosoa );
  auto position_1 = Cabana::slice<0>( position_1_aosoa );
  auto force_1 = Cabana::slice<0>( force_1_aosoa );

  // =====================================================
  // boundary particles or second set of particles (set 2)
  // =====================================================
  int num_tuple_2 = 40;

  // AoSoA
  AoSoA_int id_2_aosoa( "id_2", num_tuple_2 );
  AoSoA_double mass_2_aosoa( "mass_2", num_tuple_2 );
  AoSoA_double3 position_2_aosoa( "position_2", num_tuple_2 );
  AoSoA_double3 force_2_aosoa( "force_2", num_tuple_2 );

  // Slices
  auto id_2 =  Cabana::slice<0>( id_2_aosoa );
  auto mass_2 = Cabana::slice<0>( mass_2_aosoa );
  auto position_2 = Cabana::slice<0>( position_2_aosoa );
  auto force_2 = Cabana::slice<0>( force_2_aosoa );

  /*
    Initialize particles with intial properties, such as: position, velocity,
    static
  */
  setup_particles_with_initial_properties_1(&position_1, &mass_1);
  setup_particles_with_initial_properties_2(&position_2, &mass_2);

  // ================================================
  // create the neighbor list for set 1
  // ================================================
  double grid_min[3] = { -1.0, -1.0, -1.0 };
  double grid_max[3] = { 1.0, 1.0, 1.0 };
  double neighborhood_radius = 0.7;
  double cell_ratio = 1.0;
  using ListAlgorithm = Cabana::FullNeighborTag;
  using ListType =
    Cabana::VerletList<MemorySpace, ListAlgorithm, Cabana::VerletLayout2D>;
  ListType verlet_list_1( position_1, 0, position_1.size(), neighborhood_radius,
			  cell_ratio, grid_min, grid_max );
  // ================================================
  // create the neighbor list for set 2
  // ================================================
  ListType verlet_list_2( position_2, 0, position_2.size(), neighborhood_radius,
			  cell_ratio, grid_min, grid_max );

  auto dt = 1e-2;
  auto tf = 1.;
  auto t = 0.;
  int nsteps = tf / dt;
  // Main timestep loop
  for ( int step = 0; step < nsteps; step++ )
    {
      // compute the neighbor lists
      ListType verlet_list_1( position_1, 0, position_1.size(), neighborhood_radius,
			      cell_ratio, grid_min, grid_max );
      ListType verlet_list_2( position_2, 0, position_1.size(), neighborhood_radius,
			      cell_ratio, grid_min, grid_max );

      // compute the forces on set 1 particles due to interaction with set 1 particles
      compute_force(&force_1, &position_1, &mass_1, &position_1, &mass_1, &verlet_list_1);
      // compute the forces on set 1 particles due to interaction with set 2 particles
      compute_force(&force_1, &position_1, &mass_1, &position_2, &mass_2, &verlet_list_2);

      // now compute the force on particles 2 due to the interaction with particles 2
      compute_force(&force_2, &position_2, &mass_2, &position_1, &mass_1, &verlet_list_1);

      // update the position and velocity
      update_state(&position_1, &velocity_1, &force_1, &mass_1, dt);
      update_state(&position_2, &velocity_2, &force_2, &mass_2, dt);

      // update the time
      t += dt;
    }

}


int main( int argc, char *argv[] )
{

  Kokkos::ScopeGuard scope_guard( argc, argv );

  DEM_run();

  return 0;
}
```

From the code block, we can see that, we have create two sets of particles, as well as corresponding `verlet_list`s. With the current `cabana` routines, I couldn't find how to handle the above computations. I think, one way to solve this could, be returning the list of neighbour particles based on based on the position. This way, we can get the source neighbouring particle indices based on the position of the `destination` particle position. 

Is there any other way to approach this problem? To further add, the final problem, I am going to solve, has rigid bodies, which can change shape, adaptive fluid particles, rigid bodies whose centers will interact with other rigid bodies and etcetera.

**Comment by streeve** [comment]
As you've noted we do not currently enable creating neighbor lists across multiple particle lists. I'll put some thought into what those interfaces could look like, but the next paragraph is how I would write this now.

In all the Cabana applications I've written so far I keep a single particle list regardless of the physics or species of each particle. Depending on the situation I either track the type in a particle field and apply different operations for each type within a single kernel OR (especially for a boundary) where things don't change (often) in the simulation keep a separate index list of which particles are of each type and loop over the lists separately with different kernels. You could also sort the particles to keep those different types in contiguous blocks of memory for better access in the latter case. But for all of this there's one neighbor list that includes all the particle types

**Comment by dineshadepu** [comment]
Thanks @streeve . I want to add that by dividing the problem into different number of sets of particles will help me with the post-processing and visualization as well. I will try to play around a little to see if I can modify the code, such that I can add a function based on the position of the particles to return the nearest neighbours. I would like to give a reference implementation of neighbour list algorithm, where neighbours are returned based on the position of the particle. 

The algorithm described in this video https://www.youtube.com/watch?v=D2M8jTtKi44&t=388s works on gpu as well as cpu. The corresponding code is given at  https://github.com/matthias-research/pages/blob/master/tenMinutePhysics/11-hashing.html . The neighbours of a given particle are computed based on the position of the particle, as described in this function [here](https://github.com/matthias-research/pages/blob/master/tenMinutePhysics/11-hashing.html#L113). 

I will keep this issue open, and will implement `SPH` and `DEM` numerical techniques based on the current routines for now and update them as soon as we can handle different particle sets.

**Comment by streeve** [comment]
The `VerletList` implementation is very similar to what you linked, a grid-accelerated neighbor search based on position. But this is still distinct from being able to generate neighbors across multiple lists of particles. 

In order to do what you're suggesting we would need to store, in addition to the neighbor index, the particle list index per central particle. This would require many new interfaces across neighbor creation and iteration and quite a bit of development time. To your point about post/viz we support operating on partial ranges of particles that are within the same list (e.g. HDF5 output) for cases of different particle types (which would need to be sorted), but I understand what you mean 

It may be worth looking at the `LinkedCellList` as well - here the neighbors are not stored directly (avoiding the issues I just mentioned), but instead each particle is assigned to a bin and for each particle you can loop over the nearby bins.

**Comment by dineshadepu** [comment]
Yes, I agree with you @streeve . It is clear for me now, that by looping through the given range of particles I can selectively compute the forces on the particles. This eliminates lot of unnecessary computation. I will get started and get back to you regarding the sorting of the particles once the basic implementation is ready.

**Comment by streeve** [comment]
Sorry, I thought I had responded to your last question here. One place to see a particle loop is here: https://github.com/ECP-copa/Cabana/blob/9043086fb7544e14208f780d73b0b66b8ef1a200/core/src/Cabana_ParticleInit.hpp#L101

**Comment by streeve** [comment]
Feel free to reopen as needed
