### ISSUE TITLE
CMake error for installation of HDF5

### ISSUE THREAD

**Issue by kwitaechong** [ECP-copa/Cabana#657]
during configuration of Cabana, create wrong version of HDF5 version at

`~/install/Cabana/lib/cmake/Cabana/CabanaConfig.cmake` at line 47 with ths error messages,

```CMake Error at /opt/local/share/cmake-3.24/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  find_package called with invalid argument "1.14.1-2"
Call Stack (most recent call first):
~/install/Cabana/lib/cmake/Cabana/CabanaConfig.cmake:47 (find_dependency)
  CMakeLists.txt:18 (find_package)

**Comment by streeve** [comment]
@kwitaechong can you add the full error message?

**Comment by dineshadepu** [comment]
Hi @kwitaechong . I have recently installed Cabana on Ubuntu 22 with parallel hdf5. I have documented the order of installation of each package at https://gist.github.com/dineshadepu/6c3fac71d5d6c0035df079c6c2e44cf8 . You can follow it if you are facing any issues.

**Comment by dineshadepu** [comment]
@streeve @kwitaechong Yes, I face the same issue while installing cabana with parallel HDF5. 

I think solution for this is, I have manually removed the hdf5 version number (here it is 1.14) in cmake file of cabana. The package find command somehow generated this additional version number. A fix if this would be good.

**Comment by dineshadepu** [comment]
![image](https://github.com/ECP-copa/Cabana/assets/13584458/647c0acd-03df-4742-955b-23659ffcaf8a)


Here is my manually corrected cmake file, which compiles and runs Cabana properly with hdf5.

**Comment by kwitaechong** [comment]
Yes, that manual fix correct this issue. Thanks

**Comment by streeve** [comment]
@brtnfld any ideas here?
