### ISSUE TITLE
Check version of Cabana during CMake configure?

### ISSUE THREAD

**Issue by cwsmith** [ECP-copa/Cabana#706]
Hello,

As a developer of a library that depends on Cabana, is there a way to check the installed Cabana version during CMake configure (i.e., `cmake -S myProject`)?  It looks like the CMake project version hasn't been changed in a while:
https://github.com/ECP-copa/Cabana/blame/master/CMakeLists.txt#L18

Thank you.

**Comment by streeve** [comment]
You're right - the value has been unhelpful (and unchanged) since 0.3. Let me look into the best way to fix this

**Comment by streeve** [comment]
I opened #708 for now; will add patch releases for the other minor versions as well

**Comment by streeve** [comment]
@cwsmith The current master is fixed - do you need previous version support (prior to 0.6.01) or can you just use that?

**Comment by cwsmith** [comment]
Having the current version (and future versions) is enough for us.  Thank you!

**Comment by streeve** [comment]
Great - 0.6.1 will be out in the coming weeks
