### ISSUE TITLE
Installing Cabana with PGI on Summit

### ISSUE THREAD

**Issue by ascheinb** [ECP-copa/Cabana#72]
Installation with pgi/18.10 was successful after the following 3 changes:

- In gtest/gtest/gtest-all.cc, I had to change `#include "gtest/gtest.h"` to `#include "gtest.h"`
- After running cmake, I had to remove an instance of the compiler flag `-fast`
- and change instances of `--c++11` to `--std=c++11`

**Comment by sslattery** [comment]
@ascheinb are there changes needed to the code and/or build system to facilitate this?

**Comment by ascheinb** [comment]
Maybe. Until recently, I hadn't touched Kokkos/Cabana on Summit since I got it working. Last week I tried to build the most recent version (in a separate location, thankfully) and encountered some problems. They probably aren't serious and I just need to spend a little time on it, but haven't gotten around to it this week.

**Comment by ascheinb** [comment]
I'll update when I do try to reinstall - I assume it's not urgent on your side...?

**Comment by dalg24** [comment]
There was some traffic last week on Kokkos issues about building on Summit with PGI.

**Comment by sslattery** [comment]
Not urgent but just want to follow up to see what the status is and if we need code changes to support.

**Comment by ascheinb** [comment]
I have been working on this on a non-urgent basis, but Summit just had an upgrade and they recommend we recompile everything, so it's now urgent that I recompile Cabana. Unfortunately, I am having problems doing so with PGI. (It worked with gcc, but I need it with PGI for XGC.) Could someone take a look at this with me?

Kokkos compiles fine with PGI.

I run the following script in Cabana/build:

```
export KOKKOS_SRC_DIR=/ccs/home/scheinberg/Software/kokkos
export KOKKOS_INSTALL_DIR=$KOKKOS_SRC_DIR/install
export NVCC_WRAPPER_DEFAULT_COMPILER=mpiCC
export CABANA_INSTALL_DIR=/ccs/home/scheinberg/Software/Cabana/install

cmake \
     -D CMAKE_BUILD_TYPE="Release" \
     -D CMAKE_PREFIX_PATH=$KOKKOS_INSTALL_DIR \
     -D CMAKE_INSTALL_PREFIX=$CABANA_INSTALL_DIR \
     -D CMAKE_CXX_COMPILER=$KOKKOS_SRC_DIR/bin/nvcc_wrapper \
     -D Cabana_ENABLE_TESTING=ON \
     -D Cabana_ENABLE_EXAMPLES=ON \
     -D Cabana_ENABLE_Serial=ON \
     -D Cabana_ENABLE_OpenMP=ON \
     -D Cabana_ENABLE_Cuda:BOOL=ON \
     .. ;
```

When I make install, I get:
```
Scanning dependencies of target cabanacore
[  1%] Building CXX object core/src/CMakeFiles/cabanacore.dir/impl/Cabana_Version.cpp.o
g++: error: unrecognized command line option '-fast'

```

This raises 2 questions:
Where does "-fast" come from? I grepped for it in kokkos and Cabana, it is only generated when I run that cmake command. 
Why does it say g++ rather than pgi?
```
$ which mpiCC
/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/pgi-18.10/spectrum-mpi-10.3.0.0-20190419-femacxmvjgm5iwt444yxbk2merwcz6s6/bin/mpiCC
```

Thanks!

**Comment by ascheinb** [comment]
I just tried setting MAKE_BUILD_TYPE="Debug", which turns -fast off, and I get a little further:

```
Scanning dependencies of target cabanacore
[  1%] Building CXX object core/src/CMakeFiles/cabanacore.dir/impl/Cabana_Version.cpp.o
[  2%] Linking CXX static library libcabanacore.a
[  2%] Built target cabanacore
Scanning dependencies of target cabana_core_gtest
[  3%] Building CXX object core/unit_test/CMakeFiles/cabana_core_gtest.dir/__/__/gtest/gtest/gtest-all.cc.o
g++: error: unrecognized command line option '--c++11'
make[2]: *** [core/unit_test/CMakeFiles/cabana_core_gtest.dir/__/__/gtest/gtest/gtest-all.cc.o] Error 1
make[1]: *** [core/unit_test/CMakeFiles/cabana_core_gtest.dir/all] Error 2
```

PGI format is `-std=c++11`, not `--c++11`, so again it looks like it's trying to compile with PGI, but running into g++ flags... and yet strangely, it's `g++: error` not `pgc++ error`...

**Comment by ascheinb** [comment]
Sorry, I have this backwards. PGI accepts -std=c++11 and --c++11, while g++ accepts only -std=c++11. Similarly, -fast is a PGI flag. So the problem is simpler than I was posing:

For some reason, I am compiling with g++ when I want to be compiling with pgi. And all the flags are for PGI, so they should be fine once I figure out how to set the compiler to be PGI.

**Comment by ascheinb** [comment]
For completeness, here is the output from the cmake configure:

```
-- The CXX compiler identification is PGI 18.10.1
-- Check for working CXX compiler: /ccs/home/scheinberg/Software/kokkos/bin/nvcc_wrapper
-- Check for working CXX compiler: /ccs/home/scheinberg/Software/kokkos/bin/nvcc_wrapper -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - failed
-- Found KOKKOS: /ccs/home/scheinberg/Software/kokkos/install  
-- Found OpenMP_CXX: -mp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- The CUDA compiler identification is NVIDIA 9.2.148
-- Check for working CUDA compiler: /sw/summit/cuda/9.2.148/bin/nvcc
-- Check for working CUDA compiler: /sw/summit/cuda/9.2.148/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Enable Devices: Serial;OpenMP;Cuda
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components:  doxygen missing components:  dot
-- Performing Test COMPILER_SUPPORTS_MARCH
-- Performing Test COMPILER_SUPPORTS_MARCH - Failed
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- Cabana Revision = '8558c64794ad38caf07862da4d4fe7eba71b950c'
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found CUDA: /sw/summit/cuda/9.2.148 (found version "9.2") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Checking for module 'scafacos'
--   No package 'scafacos' found
-- Configuring done
-- Generating done
-- Build files have been written to: /ccs/home/scheinberg/Software/Cabana/build
```

**Comment by dalg24** [comment]
Please tell us how you configured Kokkos before you installed it.

And then when you build Cabana do `make VERBOSE=1`

**Comment by sslattery** [comment]
Yes - did you rebuild kokkos? Looks like you are still pulling in the old 9.2 cuda. Did you also update your nvcc wrapper settings to point to PGI instead of GCC?

**Comment by dalg24** [comment]
@ascheinb Make sure that `NVCC_WRAPPER_DEFAULT_COMPILER` is set in your environment at build time (when you call `make`). It is properly set when you configure but it won't be in your env after you execute the script (unless you sourced it?)

**Comment by ascheinb** [comment]
Thanks @dalg24 - that was the issue. I'm still not able to compile yet but will see how far I get.

**Comment by ascheinb** [comment]
Actually, XGC seems to run fine with kokkos/cabana both compiled with g++. So I'm inclined to just leave things that way rather than deal with pgc++.

**Comment by sslattery** [comment]
Closing as XGC is moving away from PGI
