### ISSUE TITLE
Excess internal node inclusion in the BoundaryIndexSpace with Node entities

### ISSUE THREAD

**Issue by lebuller** [ECP-copa/Cabana#724]
A `boundaryIndexSpace` over `Node` entities includes a number of nodes on the exterior of the grid equal to the halo width as well as one additional internal node. This additional node should not be included when looping over boundaries for the purpose of setting boundary conditions.

As a sidenote, the usage and motivation for using halos in `boundaryIndexSpaces` and how it relates to the halo as used in `sharedIndexSpaces` needs to be discussed

**Comment by streeve** [comment]
@patrickb314 @colemanjs you've both used the `boundaryIndexSpace` with `Node` in its current form - do you have any issues proposed change? This is motivated to ensure consistency between internal and boundary nodes for a Poisson solve

**Comment by streeve** [comment]
Closing this - we instead updated our internal usage of the `boundaryIndexSpace` (for posterity, using a halo width zero for a `Node` BC exactly on the boundary and halo width one for `Cell` on one of the `Own/Ghost` side

Definitions of each `boundaryIndexSpace` is consistent across entities and `Own/Ghost`
