### ISSUE TITLE
How to update the neighbours, which the positions are being updated?

### ISSUE THREAD

**Issue by dineshadepu** [ECP-copa/Cabana#748]
Hey everyone,

I'm currently working on implementing an SPH-DEM solver in Cabana to analyze particle dispersion in fluid tanks. I've managed to write the code for both the SPH and DEM components, where the DEM particles follow rigid body dynamics and interact with SPH fluid particles through discretized dummy particles.

This is not a bug but a question I am dealing with. I'm facing a common challenge in both components during the time loop. I need to update the neighbors for each particle, but I'm struggling with the implementation. Here is part of my code:

```cpp

  ListType verlet_list( aosoa_position, 0,
			aosoa_position.size(), neighborhood_radius,
			cell_ratio, grid_min, grid_max );

  // Main timestep loop
  for ( int step = 0; step < steps; step++ )
    {
      rigid_body_stage_1(rb, dt);
      rigid_body_particles_stage_1(aosoa, rb, dt, rigid_limits);

      rigid_body_stage_2(rb, dt);
      rigid_body_particles_stage_2(aosoa, rb, dt, rigid_limits);

      // Compute the neighbours
      ListType verlet_list( aosoa_position, 0,
			    aosoa_position.size(), neighborhood_radius,
			    cell_ratio, grid_min, grid_max );

      compute_force_on_rigid_body_particles(aosoa, dt,
					    &verlet_list,
					    rigid_limits);

      body_force_rigid_body(rb, gravity, dt);
      compute_effective_force_and_torque_on_rigid_body(rb,
						       aosoa);

      rigid_body_stage_3(rb, dt);
      rigid_body_particles_stage_3(aosoa, rb, dt, rigid_limits);

      if ( step % print_freq == 0 )
	{
	  std::cout << "Time is:" << time << std::endl;
	  output_data(aosoa, num_particles, step, time);
	  output_rb_data(rb, no_of_bodies, step, time);
	}

      time += dt;

    }
```

Here, I am creating the `verlet_list` variable every time in the loop, and I am not sure if it is hampering the performance. Is there any way to just update it with the updated positions, provided it working on all the architectures independently? 

I will share the fully code in the next comment. Thank you so much for the help :) .

**Comment by streeve** [comment]
This will absolutely affect performance in two main ways: first constructing every step will do a lot of initialization memory allocation that doesn't need to be re-done, second presuming a relatively consistent neighborhood size re-iteration during search can be minimized. 

After construction, the loop can call: 
```verlet_list.build( aosoa_position, 0, aosoa_position.size(), neighborhood_radius, cell_ratio, grid_min, grid_max );```

You can also call:
```
max_neigh_guess = 100; // could also depend on previous max_neighbor count
verlet_list.build( aosoa_position, 0, aosoa_position.size(), neighborhood_radius, cell_ratio, grid_min, grid_max, max_neigh_guess );
```
for the additional benefits if you have some way to estimate how many will be found in the next neighbor search. The more you overallocate the more unused memory you will have, but you will avoid reallocation more often.

**Comment by dineshadepu** [comment]
Thank you Sam. I will close the issue as it addresses the problem. However, I have a performance related problem, which I will raise in a different issue.
