### ISSUE TITLE
Reuse LinkedCellList in VerletList Construction

### ISSUE THREAD

**Issue by sslattery** [ECP-copa/Cabana#75]
If a user has already created a LinkedCellList for another purpose they should be able to reuse it when building a VerletList as long as that LinkedCellList was built with the same parameters.

**Comment by sslattery** [comment]
I'm starting to question whether this is a good thing to do. There are several issues:

1. If a `LinkedCellList` is created outside the `VerletList` we would either have to be very careful to ensure it has consistent construction or infer the properties of the verlet list from the linked cell list. Any consistency issues can created unexpected results both in terms of correctness and performance.

2. If a `LinkedCellList` is created outside the `VerletList` *and* is used to permute the particles such that they are now ordered by cell (which is why you would create a `LinkedCellList` in the first place) then the verlet list made from that linked cell list would technically be wrong. The reason for this is that the current verlet list implementation assumes that a cell list is only used as an acceleration structure and *is not* used to permute the particles. Thus, particles permuted with a linked cell list would actually present invalid indices to the verlet list implementation. To solve this we would have to essentially have 2 verlet list implementations, one where the particles are not permuted and one where they are. 

Based on the fact that these 2 points cause great complications *and* it has been indicated to me by @sjplimp that the linked cell list is only used to permute particles on a time scale less frequently than a verlet list is constructed, I am thinking we might not want to do this.

@streeve @sjplimp Opinions on this?

**Comment by sjplimp** [comment]
Not following this nomenclature precisely.  I think of a LinkedCellList (LCL)
as not reordering the particles, but simply assigning them to cells,
and storing linked lists (one per cell) that have the indices of the particles
in that cell.  This can be done with one vector of length N = # of particles,
plus one vector of length M = # of cells.  And one pass thru the particles.
Though I'm not sure how Kokkos threads that.   Stan could comment on this.
The LCL is created once per reneighboring and is only used to create
the Verlet (neighbor) list.  Then it can be discarded.

I think of reordering the particles as a "sort".  It could also use a LCL
(possibly with different size bins) to determine what particle to move where.
In MD we would typically do the sort rarely (e.g. every 1000 steps),
and the reneighbor frequently (every 10-20 steps).

**Comment by sslattery** [comment]
Thanks @sjplimp - that clarifies my thoughts and is consistent with our previous discussions. The `LinkedCellList` in Cabana is essentially what you have described - we don't reorder particles but we have a list of which particles are in which cells and use this to accelerate construction of the Verlet list. That same data structure, as you have indicated, can also be used to sort the particles based on their cell location.

@streeve Based on the infrequency of sorting vs. neighbor list construction in the production application *and* the fact that the linked cell list used for sorting vs. neighbor list construction may likely have different bin sizes, I don't think we should support this functionality. Do you agree?

**Comment by sjplimp** [comment]
One more thought - it's possible that for GPUs, sorting (much) more often is desirable.  Again,
Stan could comment on that better than I.  Can't seem to include him
in this with @stanmoore1.  I assume Cabana is going to include particle sorting as an operation?

**Comment by sslattery** [comment]
Yes sorting is already included - both with linear keys as well as using the `LinkedCellList` for spatial sorting. I would say unless the binning structure is identical and the sorting occurs at the same frequency as the neighbor list construction then we likely don't need to support building the verlet list with existing binning data.

**Comment by streeve** [comment]
Yes, I agree that the benefits don't seem to justify the cost. Stan's input aside, I think it's best to not include.

**Comment by sslattery** [comment]
@stanmoore1 any thoughts? Otherwise I will close this as a won't fix.
