### ISSUE TITLE
CMAKE v3.28 HDF5 Configuration variable

### ISSUE THREAD

**Issue by ominusliticus** [ECP-copa/Cabana#760]
Currently, if one is using a version of [CMake greater than version 3.26](https://github.com/ECP-copa/Cabana/blob/80b0194b687024bcbd850f1491e345ac94baf64a/CMakeLists.txt#L109), the configuration automatically sets the option `Cabana_ENABLE_HDF5` to `true` even if the user has supplied `Cabana_REQUIRE_HDF5=false` argument. Is there a reason for this?

**Comment by junghans** [comment]
The `REQUIRED` option only enforces that the package was actually found. To disable a package completely even though it was found on the system, one needs to use the `CMAKE_DISABLE_FIND_PACKAGE` option.

**Comment by streeve** [comment]
Updated the build instructions to clarify

**Comment by streeve** [comment]
Closing - feel free to reopen if you are still having configuration issues
