### ISSUE TITLE
Support for Interaction Between Spherical Particles and a Triangulated Mesh

### ISSUE THREAD

**Issue by dineshadepu** [ECP-copa/Cabana#763]
Hi all,

Firstly, I want to express my gratitude for the excellent work on Cabana and its associated codebases like CabanaPD, CabanaMD, ExaMPM, Picasso, etc. These tools have been incredibly helpful and enjoyable to use in developing my Discrete Element Method (DEM) simulations (https://github.com/dineshadepu/CabanaDEM). It brings immense joy to work with it. 

Coming to my question, I am currently able to model the interactions between particles, as Cabana inherently supports retrieving the neighbors of a given particle. I am looking to extend the current functionality to model interactions between spherical particles and a triangulated mesh. The mesh currently acts as a static boundary, but I plan to allow it to move and behave as a rigid body in future implementations. I need to check the interaction between a given particle and the triangle. Since there will be so many triangles, I need to find the nearest triangles and carry out my collision algorithm. Do you have any input on how to proceed with the implementation and design? 

Thank you,
Dinesh.

**Comment by dineshadepu** [comment]
I came up with an idea and will proceed with it. Will reopen if I run into any issues.

**Comment by dalg24** [comment]
You could look into using ArborX for this.

**Comment by streeve** [comment]
Hey Dinesh, glad to hear things are going well - to Damien's point, the Picasso library uses Cabana and ArborX to do something like this. https://github.com/picassodev/picasso/ We're working on improved documentation actively right now

**Comment by dineshadepu** [comment]
Thank you Damien and Sam. I will follow the `traingle_intersection.cpp` example of ArborX.
