### ISSUE TITLE
Unable to Access Time Data from XMF Output Files

### ISSUE THREAD

**Issue by dineshadepu** [ECP-copa/Cabana#764]
Hi all,

I have run a simulation and generated output files in XMF format (HDF5). For validation purposes, I need to plot the force on a given particle against time and compare it with experimental results. However, I am having difficulty accessing the time data from the h5 output files.
 
I have reviewed the documentation but haven't found the information needed to extract the time data. Below is a snippet of my current post-processing code:

```
import h5py
import numpy as np

f = h5py.File("particles_100.h5", "r")
# get the force of first particle in x direction
fx = f["forces"][0][0]
```

Any help on this? In case if it is missing, I can write a small documentation and give a PR on how to do postprocessing of basic cases. 

Thank you.

**Comment by streeve** [comment]
I believe you can extract with f["Time"], but I haven't used the hdpy package much. Sounds good on the simple postprocess example

**Comment by dineshadepu** [comment]
Thanks the response, Sam. `f["Time"]` is not part of the keys of the `h5` file Cabana outputs. After some look up, I found that `Cabana` saves the "Time" as an attribute, since it is a scalar, as can be seen here

```
https://github.com/ECP-copa/Cabana/blob/master/core/src/Cabana_HDF5ParticleOutput.hpp#L661
```

Attributes can be accessed as following with h5 package, 
```
https://docs.h5py.org/en/stable/quick.html#attributes
```
with out case, it is as

```
    f.attrs["Time"]
``` 

Writing these out so that other can use at some point. I will add a section to the wiki and give a PR on how to do some basic post processing. 

Dinesh.

**Comment by dineshadepu** [comment]
Hi @streeve . I checked with github `wiki`, turns out I can't clone it and give a PR. So, I am writing it here. Please do add it to the `wiki` section, if you find it suitable. Also, can you please document on how you would do the postprocessing, this would help me to attain better reproducible research (which is I am currently looking at for my CabanaDEM simulations). 

Many thanks.

**Comment by dineshadepu** [comment]
# Documentation for Analyzing Particle Simulation Output Using HDF5

This section provides a step-by-step guide on how to analyze and visualize the
output data from a particle simulation using HDF5 files. We will demonstrate how
to load the results, process the data, and plot the variation of a specific
quantity (in this case, the position of a particle) over time using Python
libraries such as `h5py` and `matplotlib`.

## Simulation Overview

As an example, we consider the hdf5 output example of `Cabana`. In our 
simulation, we have 9 particles initially placed at equal distances from
each other. Each particle starts with a unit velocity along the x-axis. The
simulation runs for a total of 1 second, with a time step of 0.01 seconds. Data
is output at intervals of 10 timesteps, generating a total of 10 HDF5 files. The
filenames are of the format `particles_XX.h5`, where `XX` is the output step
number.

## Prerequisites

To follow this guide, you need the following:

* Python 3.10 or higher
* h5py library for handling HDF5 files
* matplotlib library for plotting
* Simulation output files in HDF5 format

You can install the required libraries using pip:

```bash
pip install h5py matplotlib
```

## Running the Simulation

To run the simulation, use the following commands in your terminal:
```bash
=> cd /home/user/Cabana/build
=> ./example/core_tutorial/13_hdf5_output/HDF5Output
```

During execution, the program will generate output files and provide console
output as shown below:
```bash
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false

Cabana HDF5 output example

Output for step 0/100
Output for step 10/100
Output for step 20/100
Output for step 30/100
Output for step 40/100
Output for step 50/100
Output for step 60/100
Output for step 70/100
Output for step 80/100
Output for step 90/100
```

This process will produce a series of HDF5 and XMF files representing the
simulation state at each output step.

## Accessing the Output Data

The simulation produces files named __particles_XX.h5__ and __particles_XX.xmf__, where __XX__ is the step number.
Our objective is to analyze the position data of the first particle (with index __0__) over time.

### Step 1: Set Up the Environment
We will use ipython to run the analysis interactively. Launch ipython from your terminal:

```bash
=> ipython
```

Load the required packages:

```python

import h5py
import matplotlib.pyplot as plt
import os
```
### Step 2: Locate and Sort the Output Files

We need to locate the output files and sort them in ascending order based on the timestep:

```python
directory_name = "./"
files = [filename for filename in os.listdir(directory_name)
         if filename.startswith("particles") and filename.endswith("h5")]
files.sort()

files_num = []
for f in files:
    f_last = f[10:]  # Extract the step number from the filename
    files_num.append(int(f_last[:-3]))  # Remove the ".h5" extension
files_num.sort()

sorted_files = []
for num in files_num:
    sorted_files.append(f"particles_{num}.h5")

files = sorted_files
```
### Step 3: Extract and Plot the Position Data

We loop through each file, extract the position data of the first particle, and plot it against time:

```python

position = []
time = []

for f in files:
    with h5py.File(directory_name + f, "r") as file:
        position.append(file["positions"][0][0])  # Access the x-position of the first particle
        time.append(file.attrs["Time"])  # Extract the simulation time from attributes

plt.plot(time, position, label="Position")
plt.xlabel("Time (s)")
plt.ylabel("Position (m)")
plt.title("Variation of Particle Position Over Time")
plt.legend()
plt.grid(True)
plt.show()
```
### Explanation of the Code:

* **File Handling**: We use h5py to open each HDF5 file and extract the position data for the first particle. The with statement ensures that each file is properly closed after use.
* **Data Extraction**: The position is stored in the dataset __positions__, where we select the first particle's x-position (__index [0][0]__). The simulation time is accessed from the file's attributes.
* **Plotting**: We use matplotlib to create a line plot of the particle's position over time. The plot is customized with labels, a title, a legend, and a grid for better readability.


![position_vs_time](https://github.com/user-attachments/assets/00e13b4a-0ab5-489a-9645-5e48e65f36d4)




## Conclusion

This document provides a complete workflow for analyzing simulation data stored
in HDF5 files. By following these steps, you can visualize how specific
quantities, such as the position of a particle, vary over time in your
simulations. You can extend this approach to analyze and visualize other types
of data as needed.

**Comment by streeve** [comment]
@dineshadepu I was a bit slow on this, but pushed your example to the wiki
