### ISSUE TITLE
Outdated Links to Cajita in the Grid Wiki

### ISSUE THREAD

**Issue by dineshadepu** [ECP-copa/Cabana#767]
Hello everyone,

I've noticed that the Wiki page on Grid contains several outdated links to Cajita, including links to unit tests and examples. Unfortunately, I don't have access to edit the Wiki, so I'm unable to submit a pull request to fix these links. I'm leaving this note here for reference so that someone with editing permissions can address this issue.

Thank you,
Dinesh

**Comment by streeve** [comment]
Thanks for pointing this out - I'll fix briefly. And just a note, that we have plans to move to a github.io site which would support PRs for updates like this

**Comment by streeve** [comment]
Fixed
