### ISSUE TITLE
ArborX neighbor interface broken on master

### ISSUE THREAD

**Issue by streeve** [ECP-copa/Cabana#777]
Nightly and docker build failures

**Comment by streeve** [comment]
@aprokop is this a quick fix?

**Comment by aprokop** [comment]
We are breaking backwards compatibility right now, doing refactoring for ArborX 2.0. Stick with 1.7 version if you want backwards compatibility. I can create a patch for Cabana to use ArborX 2.0 interface, so you can switch to it early. That would mean requiring ArborX 2.0.

**Comment by streeve** [comment]
I'll need to check with some users first, so for now we'll keep 1.7
