### ISSUE TITLE
Saving Output Files to a Folder and Resolving Visualization Issues in ParaView

### ISSUE THREAD

**Issue by dineshadepu** [ECP-copa/Cabana#802]
Hi all,

I am currently saving the output data to a folder for better post-processing, so that I can automate the results. An example of this usage can be found it here (https://github.com/exaphysics/CabanaDEM, https://github.com/ExaPhysics/CabanaDEM/blob/master/automate.py). I use a python software called "automan", using this, by simply running 
```sh
python automate.py 
```
I can run all the examples and do the postprocessing as well. 

Coming to the issue,  here’s what I did to modify the output behavior:

We write the output using the following code:
(please note I am using the HDF5 output example from Cabana, to explain issue. My original implementation can be found at 
https://github.com/ExaPhysics/CabanaDEM/blob/master/src/CabanaDEM_Particles.hpp#L308)
```cpp
Cabana::Experimental::HDF5ParticleOutput::writeTimeStep(
    h5_config,
    "particles", MPI_COMM_WORLD, step, time,
    num_particles, positions, ids, velocity, radius );
```

To save the output files in a folder (e.g., `junk`), I changed the path like this:

```cpp
Cabana::Experimental::HDF5ParticleOutput::writeTimeStep(
    h5_config,
    "junk/particles", MPI_COMM_WORLD, step, time,
    num_particles, positions, ids, velocity, radius );
```

I ensured that the folder (`junk`) exists before running the program. The files are indeed saved in the specified folder. However, I encountered an issue when trying to visualize these files using `paraview`. The viewer crashes with an error indicating a "bad file descriptor." 

I’m unsure of the root cause but would like a solution that lets me save files to a folder while ensuring they remain compatible with `paraview` for visualization. I am not sure how exactly to tackle this. But I do want to save the files in a folder and able to visualize them without any issue. 

Can you please help me with this issue? Thank you so much.

**Comment by streeve** [comment]
The input for saving to HDF5 only supports filenames, not folders. You can run each case from the folder of interest or we would need to expand the filesystem support

**Comment by dineshadepu** [comment]
Ohh, okay. Sure @streeve . I think for now, I will change the directory and run the cases. Please do add the filesystem support if you think it will be helpful. 

Thank you for the help :) .
