### ISSUE TITLE
slicing is broken for non-UVM CUDA

### ISSUE THREAD

**Issue by ibaned** [ECP-copa/Cabana#86]
There is a bad `view(0).template ptr<M>()` pattern being used to get pointers for slices. `view(0)` is an illegal access on the CPU. There should be something like `SoA::static_ptr` that can be used as `soa_type::template static_ptr<M>(view.data())`.

**Comment by rfbird** [comment]
This is tied to #80. We're working on a demo fix now..

**Comment by sslattery** [comment]
I have a branch in progress for conversion to the Cuda space that addresses this issue and cleans unit tests by using deep copy to pull test data to the host. My plan was to do a PR soon.

**Comment by sslattery** [comment]
@ibaned Thanks for the fix. This was similar to my approach (also static) but I like yours better. I have added you and @rfbird as co-authors in #88 for commit f2cbf323500962997cc6f083b83e6fd85437be66

**Comment by sslattery** [comment]
@ibaned I suggest closing #87 in lieu of #88 which will add more support for CUDA builds.

**Comment by ibaned** [comment]
@sslattery agreed
